const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});const external=[];page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8001'))external.push(r.url())});const routes=['/','/competitions','/competition/ultegra','/competition/frontier','/competition/titan','/account','/dashboard','/admin','/merchandise','/dashboard/wins','/dashboard/orders','/dashboard/profile','/admin/create','/admin/edit/ultegra','/admin/customers','/admin/orders','/admin/draws','/unknown'];
for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:1000});for(const route of routes){await page.goto('http://127.0.0.1:8001/cast-v2/#'+route);await page.waitForSelector('h1');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width} ${route}`);assert(await page.locator('.demo-bar').isVisible());}console.log(`PASS ${routes.length} routes at ${width}px`)}
await page.goto('http://127.0.0.1:8001/cast-v2/#/competitions');await page.getByRole('button',{name:'Reels',exact:true}).click();assert.equal(await page.locator('.competition-card').count(),1);await page.getByRole('button',{name:'Shelters',exact:true}).click();assert.equal(await page.locator('.competition-card').count(),2);await page.getByRole('button',{name:'All prizes',exact:true}).click();assert.equal(await page.locator('.competition-card').count(),3);
await page.goto('http://127.0.0.1:8001/cast-v2/#/competition/ultegra');for(let i=0;i<24;i++)await page.getByRole('button',{name:'Increase preview quantity'}).click();assert.equal(await page.locator('#quantity').inputValue(),'20');assert.equal(await page.locator('#total').textContent(),'£59.80');for(let i=0;i<24;i++)await page.getByRole('button',{name:'Decrease preview quantity'}).click();assert.equal(await page.locator('#quantity').inputValue(),'1');await page.getByRole('button',{name:'5',exact:true}).click();assert.equal(await page.locator('#quantity').inputValue(),'5');await page.getByRole('button',{name:'20',exact:true}).click();assert.equal(await page.locator('#total').textContent(),'£59.80');await page.getByRole('button',{name:'Package contents',exact:true}).click();assert(await page.locator('#gallery-main').innerText().then(t=>t.includes('Package contents')));await page.getByRole('radio',{name:'Reel',exact:true}).check();assert((await page.locator('#skill-status').textContent()).includes('Not assessed'));const before=await page.locator('#countdown-value').textContent();await page.waitForTimeout(1100);assert.notEqual(await page.locator('#countdown-value').textContent(),before);assert(await page.getByRole('button',{name:'Entries unavailable · Design preview'}).isDisabled());
await page.evaluate(async()=>{const {competitions}=await import('./js/data.js');competitions[0].remaining=7;location.hash='/competition/ultegra';});await page.goto('http://127.0.0.1:8001/cast-v2/#/competition/frontier');await page.evaluate(async()=>{const {competitions}=await import('./js/data.js');competitions[0].remaining=7;location.hash='/competition/ultegra';});await page.waitForSelector('#quantity[max="7"]');assert(await page.getByRole('button',{name:'20',exact:true}).isDisabled());assert(await page.getByRole('button',{name:'10',exact:true}).isDisabled());for(let i=0;i<12;i++)await page.getByRole('button',{name:'Increase preview quantity'}).click();assert.equal(await page.locator('#quantity').inputValue(),'7');
await page.goto('http://127.0.0.1:8001/cast-v2/#/account');await page.getByRole('button',{name:'Create account',exact:true}).click();assert(await page.getByRole('button',{name:'Registration unavailable in preview'}).isDisabled());assert.equal(await page.locator('input:enabled').count(),0);await page.getByRole('link',{name:'Explore the demo dashboard'}).click();assert.equal(new URL(page.url()).hash,'#/dashboard');
await page.goto('http://127.0.0.1:8001/cast-v2/#/competitions');await page.locator('#prize-search').fill('shimano');assert.equal(await page.locator('.competition-card').count(),1);await page.locator('#prize-search').fill('missing prize');assert.equal(await page.locator('.competition-card').count(),0);assert((await page.locator('#search-status').textContent()).includes('No demonstration'));await page.locator('#prize-search').fill('');await page.locator('#prize-sort').selectOption('remaining');assert((await page.locator('.competition-card').first().innerText()).includes('Ultegra'));
await page.goto('http://127.0.0.1:8001/cast-v2/#/dashboard/orders');await page.getByRole('button',{name:'View demo receipt'}).first().click();assert((await page.locator('#receipt-preview').textContent()).includes('Not a tax invoice'));
await page.goto('http://127.0.0.1:8001/cast-v2/#/dashboard/profile');await page.getByRole('button',{name:'Preview preferences'}).click();assert((await page.locator('.form-status').textContent()).includes('Nothing saved'));
await page.goto('http://127.0.0.1:8001/cast-v2/#/admin/create');await page.getByLabel('Competition title',{exact:true}).fill('Demo draft');const dates=page.locator('input[type=datetime-local]');await dates.nth(1).fill('2026-09-01T09:00');await page.getByRole('button',{name:'Validate demo draft'}).click();assert((await page.locator('.form-status').textContent()).includes('must follow'));await dates.nth(1).fill('2026-11-01T09:00');await page.getByRole('button',{name:'Validate demo draft'}).click();assert((await page.locator('.form-status').textContent()).includes('Nothing saved'));assert(await page.getByLabel('Prize image upload disabled in demonstration').isDisabled());
await page.goto('http://127.0.0.1:8001/cast-v2/#/admin/customers');await page.locator('#customer-search').fill('unknown');assert(await page.locator('#customer-record').isHidden());await page.locator('#customer-search').fill('Alex');assert(await page.locator('#customer-record').isVisible());
await page.goto('http://127.0.0.1:8001/cast-v2/#/admin/draws');assert(await page.getByRole('button',{name:'Run draw unavailable'}).isDisabled());await page.getByRole('button',{name:'Preview winner record'}).click();assert((await page.locator('.form-status').textContent()).includes('Nothing saved'));
await page.setViewportSize({width:375,height:812});await page.goto('http://127.0.0.1:8001/cast-v2/');await page.getByRole('button',{name:'Menu'}).click();assert.equal(await page.getByRole('button',{name:'Menu'}).getAttribute('aria-expanded'),'true');await page.locator('nav').getByRole('link',{name:'Competitions',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Menu'}).getAttribute('aria-expanded'),'false');await page.screenshot({path:'/tmp/cast-v2-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8001/cast-v2/');await page.screenshot({path:'/tmp/cast-v2-desktop.png',fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(external,[]);console.log('PASS category/search/sort, empty results, galleries, quantity limits including low availability, skill preview, receipts, profile preferences, admin create/date validation, customer search, winner preview, disabled uploads/draws/entries, account tabs and mobile menu; no browser errors, failed assets or external requests');await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
